# Generated by Django 5.0.6 on 2024-07-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianmodel',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
    ]
